# Generated by Django 2.2.12 on 2024-01-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('sale', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
